### ISSUE TITLE
Not working with Android 4.0.4

### ISSUE THREAD

**Issue by soraryu** [orbotix/Sphero-Android-SDK#14]
Hey there,

on the System Requirements page you note that Sphero merely requires Android 2.2+ with Bluetooth. Running the Android SDK samples on such device (Android 4.0.4), however, throws an error in the Bluetooth LE detection stack about methods not being available ("unsupported operation").

There's a long error message:

```
10-06 18:31:40.080 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.080 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.a, referenced from method com.orbotix.le.DiscoveryAgentLE.<init>
10-06 18:31:40.090 24003-24003/? W/dalvikvm: VFY: unable to resolve static method 1757: Lcom/orbotix/le/b;.a ()Lcom/orbotix/le/b;
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.090 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.090 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.addDiscoveryChangedStateListener, referenced from method com.orbotix.le.DiscoveryAgentLE.addDiscoveryChangedStateListener
10-06 18:31:40.090 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1765: Lcom/orbotix/le/b;.addDiscoveryChangedStateListener (Lcom/orbotix/common/DiscoveryStateChangedListener;)V
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.090 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.090 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.addDiscoveryListener, referenced from method com.orbotix.le.DiscoveryAgentLE.addDiscoveryListener
10-06 18:31:40.090 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1766: Lcom/orbotix/le/b;.addDiscoveryListener (Lcom/orbotix/common/DiscoveryAgentEventListener;)V
10-06 18:31:40.090 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.addRobotStateListener, referenced from method com.orbotix.le.DiscoveryAgentLE.addRobotStateListener
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1768: Lcom/orbotix/le/b;.addRobotStateListener (Lcom/orbotix/common/RobotChangedStateListener;)V
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.connect, referenced from method com.orbotix.le.DiscoveryAgentLE.connect
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1772: Lcom/orbotix/le/b;.connect (Lcom/orbotix/common/Robot;)V
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.disconnectAll, referenced from method com.orbotix.le.DiscoveryAgentLE.disconnectAll
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1773: Lcom/orbotix/le/b;.disconnectAll ()V
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.fireRobotStateChange, referenced from method com.orbotix.le.DiscoveryAgentLE.fireRobotStateChange
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1774: Lcom/orbotix/le/b;.fireRobotStateChange (Lcom/orbotix/common/Robot;Lcom/orbotix/common/RobotChangedStateListener$RobotChangedStateNotificationType;)V
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.b, referenced from method com.orbotix.le.DiscoveryAgentLE.getConnectStrategy
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1770: Lcom/orbotix/le/b;.b ()Lcom/orbotix/le/connectstrategy/ConnectStrategy;
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.100 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getConnectedRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.getConnectedRobots
10-06 18:31:40.100 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1775: Lcom/orbotix/le/b;.getConnectedRobots ()Ljava/util/List;
10-06 18:31:40.100 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getConnectingRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.getConnectingRobots
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1777: Lcom/orbotix/le/b;.getConnectingRobots ()Ljava/util/List;
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getContext, referenced from method com.orbotix.le.DiscoveryAgentLE.getContext
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1778: Lcom/orbotix/le/b;.getContext ()Landroid/content/Context;
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getMaxConnectedRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.getMaxConnectedRobots
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1779: Lcom/orbotix/le/b;.getMaxConnectedRobots ()I
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getOnlineRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.getOnlineRobots
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1780: Lcom/orbotix/le/b;.getOnlineRobots ()Ljava/util/List;
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.getRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.getRobots
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1781: Lcom/orbotix/le/b;.getRobots ()Ljava/util/List;
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.isDiscovering, referenced from method com.orbotix.le.DiscoveryAgentLE.isDiscovering
10-06 18:31:40.110 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1782: Lcom/orbotix/le/b;.isDiscovering ()Z
10-06 18:31:40.110 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.110 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.removeDiscoveryChangedStateListener, referenced from method com.orbotix.le.DiscoveryAgentLE.removeDiscoveryChangedStateListener
10-06 18:31:40.120 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1786: Lcom/orbotix/le/b;.removeDiscoveryChangedStateListener (Lcom/orbotix/common/DiscoveryStateChangedListener;)V
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.removeDiscoveryListener, referenced from method com.orbotix.le.DiscoveryAgentLE.removeDiscoveryListener
10-06 18:31:40.120 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1787: Lcom/orbotix/le/b;.removeDiscoveryListener (Lcom/orbotix/common/DiscoveryAgentEventListener;)V
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.addRobotStateListener, referenced from method com.orbotix.le.DiscoveryAgentLE.removeRobotStateListener
10-06 18:31:40.120 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1768: Lcom/orbotix/le/b;.addRobotStateListener (Lcom/orbotix/common/RobotChangedStateListener;)V
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.a, referenced from method com.orbotix.le.DiscoveryAgentLE.setConnectStrategy
10-06 18:31:40.120 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1763: Lcom/orbotix/le/b;.a (Lcom/orbotix/le/connectstrategy/ConnectStrategy;)V
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.120 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.setMaxConnectedRobots, referenced from method com.orbotix.le.DiscoveryAgentLE.setMaxConnectedRobots
10-06 18:31:40.120 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1788: Lcom/orbotix/le/b;.setMaxConnectedRobots (I)V
10-06 18:31:40.120 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.a, referenced from method com.orbotix.le.DiscoveryAgentLE.setRadioDescriptor
10-06 18:31:40.130 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1759: Lcom/orbotix/le/b;.a (Lcom/orbotix/le/RadioDescriptor;)V
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.startDiscovery, referenced from method com.orbotix.le.DiscoveryAgentLE.startDiscovery
10-06 18:31:40.130 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1790: Lcom/orbotix/le/b;.startDiscovery (Landroid/content/Context;)Z
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Failed resolving Lcom/orbotix/le/b; interface 10 'Landroid/bluetooth/BluetoothAdapter$LeScanCallback;'
10-06 18:31:40.130 24003-24003/? W/dalvikvm: Link of class 'Lcom/orbotix/le/b;' failed
10-06 18:31:40.130 24003-24003/? I/dalvikvm: Could not find method com.orbotix.le.b.stopDiscovery, referenced from method com.orbotix.le.DiscoveryAgentLE.stopDiscovery
10-06 18:31:40.130 24003-24003/? W/dalvikvm: VFY: unable to resolve virtual method 1791: Lcom/orbotix/le/b;.stopDiscovery ()V
10-06 18:31:40.130 24003-24003/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40a2d1f8)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime: FATAL EXCEPTION: main
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.prefrontalcortex.experimental.spherostreaming/com.prefrontalcortex.experimental.spherostreaming.MainActivity}: java.lang.UnsupportedOperationException
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1978)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2003)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:123)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1169)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4446)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:  Caused by: java.lang.UnsupportedOperationException
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.orbotix.le.DiscoveryAgentLE.getInstance(SourceFile:31)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.orbotix.DualStackDiscoveryAgent.<init>(SourceFile:45)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.orbotix.DualStackDiscoveryAgent.getInstance(SourceFile:38)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.prefrontalcortex.experimental.spherostreaming.MainActivity.onCreate(MainActivity.java:80)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:4465)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1942)
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2003) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:123) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1169) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4446) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551) 
10-06 18:31:40.130 24003-24003/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by PaulTR** [comment]
Fix for the DualStackDiscoveryAgent on pre 4.4 devices coming soon.

**Comment by soraryu** [comment]
Closed, without any commit and without any changes? Why?

**Comment by PaulTR** [comment]
Read my comment from 28 days ago.

**Comment by soraryu** [comment]
I did read it, of course - that's why I'm asking :)
This repo hasn't been touched since last year, so the fix seems to be not here - where can I find it then?

**Comment by PaulTR** [comment]
Just be patient :) I've got an update coming out soon. Also, the repo was updated about five months ago.

**Comment by PVCresin** [comment]
Hurry ... up!!!

**Comment by PVCresin** [comment]
Hurryyyyyyyyyyyy Upppppppppp

**Comment by PaulTR** [comment]
This was put in under the beta branch over a month ago :)

**Comment by stubz151** [comment]
I have the Beta branch but get D/BluetoothAdapter: startLeScan(): null in my logs when trying to connect to my sphero Mini on a new Android phone.

**Comment by PaulTR** [comment]
@stubz151 Bluetooth LE isn't supported in versions of Android earlier than 4.3, which is why you'd get a null there. Not sure if the beta branch/whatever current version of the SDK out there still supports Bluetooth classic. https://source.android.com/devices/bluetooth/ble

**Comment by stubz151** [comment]
Have android 9 though. 

> @stubz151 Bluetooth LE isn't supported in versions of Android earlier than 4.3, which is why you'd get a null there. Not sure if the beta branch/whatever current version of the SDK out there still supports Bluetooth classic. https://source.android.com/devices/bluetooth/ble

I have Android 9 though. So not sure why it is not working.
