### ISSUE TITLE
java.lang.IllegalStateException: BT Adapter is not turned ON

### ISSUE THREAD

**Issue by SamYangzx** [orbotix/Sphero-Android-SDK#23]
The log is：
java.lang.IllegalStateException: BT Adapter is not turned ON
	at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:107)
	at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:102)
	at android.bluetooth.BluetoothAdapter.startLeScan(BluetoothAdapter.java:1882)
	at android.bluetooth.BluetoothAdapter.startLeScan(BluetoothAdapter.java:1799)
	at com.orbotix.le.c.run(SourceFile:26)
	at java.lang.Thread.run(Thread.java:818)

When my app fail to connect Ollie, I will reset the bluetooth first. I think it is the problem.But whether there is no protect in the code?

**Comment by rigortek** [comment]
you should check BluetoothAdapter state is STATE_ON before you star or stop scan BLE
